refactoring

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -4,6 +4,14 @@
 echo 'Welcome!'
 dotnet husky run --name welcome
 
+
+branch_name=$(git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3)
+
+if [ "branch" = "master" ]; then
+  echo "You can't push directly to master branch."
+  exit 1
+fi
+
 echo 'Prepare Release'
 dotnet msbuild -bl -p:Configuration=Release -p:Deterministic=true src/NanoDbProfiler.AspNetCore/NanoDbProfiler.AspNetCore.csproj
 
